apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clock-api
  template:
    metadata:
      labels:
        app: clock-api
    spec:

      containers:
      - name: clock-api
        image: jeffrygonzalez/business-clock-sep-2023:v1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
