apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clock-api-path
  labels:
    name: clock-api-path
spec:
  rules:
  - host: api.hypertheory.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: clock-api-service
            port: 
              number: 80
